# -*- coding: utf-8 -*-
"""calculator task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOA7lrd1YsNOu7WK16KvIIgmnuZLpgvV
"""

def calculator():
    print("\t\t\t\t-----------SIMPLE CALCULATOR--------------")
    print("Enter the numbers and choose an arithmetic operation.")

    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))
    print("Choose an operation:")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")

    operation = input("Enter the operation (+, -, *, /): ")
    if operation == '+':
        result = num1 + num2
    elif operation == '-':
        result = num1 - num2
    elif operation == '*':
        result = num1 * num2
    elif operation == '/':
        if num2 != 0:
            result = num1 / num2
        else:
            result = "Error! Division by zero."
    else:
        result = "Invalid operation!"
    print("The result is:", result)
calculator()